//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.28 at 03:07:13 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://notacarioca.rio.gov.br/WSNacional/XSD/1/nfse_pcrj_v01.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.datagrupo.buyshowloja.webservices.notafiscal.models.nfse_pcrj_v01;
