package br.com.datagrupo.buyshowloja.webservices.notafiscal.soap.wsImportClasses;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "NfseSoap", targetNamespace = "http://notacarioca.rio.gov.br/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NfseSoap {

    /**
     *
     * @param parameters
     * @return returns br.com.caelum.estoque.cliente.ConsultarNfseResponse
     */
    @WebMethod(operationName = "ConsultarNfse", action = "http://notacarioca.rio.gov.br/ConsultarNfse")
    @WebResult(name = "ConsultarNfseResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    public ConsultarNfseResponse consultarNfse(
            @WebParam(name = "ConsultarNfseRequest", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters") ConsultarNfseRequest parameters);

    /**
     *
     * @param parameters
     * @return returns br.com.caelum.estoque.cliente.ConsultarNfsePorRpsResponse
     */
    @WebMethod(operationName = "ConsultarNfsePorRps", action = "http://notacarioca.rio.gov.br/ConsultarNfsePorRps")
    @WebResult(name = "ConsultarNfsePorRpsResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    public ConsultarNfsePorRpsResponse consultarNfsePorRps(
            @WebParam(name = "ConsultarNfsePorRpsRequest", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters") ConsultarNfsePorRpsRequest parameters);

    /**
     *
     * @param parameters
     * @return returns br.com.caelum.estoque.cliente.ConsultarLoteRpsResponse
     */
    @WebMethod(operationName = "ConsultarLoteRps", action = "http://notacarioca.rio.gov.br/ConsultarLoteRps")
    @WebResult(name = "ConsultarLoteRpsResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    public ConsultarLoteRpsResponse consultarLoteRps(
            @WebParam(name = "ConsultarLoteRpsRequest", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters") ConsultarLoteRpsRequest parameters);

    /**
     *
     * @param parameters
     * @return returns
     * br.com.caelum.estoque.cliente.ConsultarSituacaoLoteRpsResponse
     */
    @WebMethod(operationName = "ConsultarSituacaoLoteRps", action = "http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps")
    @WebResult(name = "ConsultarSituacaoLoteRpsResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    public ConsultarSituacaoLoteRpsResponse consultarSituacaoLoteRps(
            @WebParam(name = "ConsultarSituacaoLoteRpsRequest", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters") ConsultarSituacaoLoteRpsRequest parameters);

    /**
     *
     * @param parameters
     * @return returns br.com.caelum.estoque.cliente.RecepcionarLoteRpsResponse
     */
    @WebMethod(operationName = "RecepcionarLoteRps", action = "http://notacarioca.rio.gov.br/RecepcionarLoteRps")
    @WebResult(name = "RecepcionarLoteRpsResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    public RecepcionarLoteRpsResponse recepcionarLoteRps(
            @WebParam(name = "RecepcionarLoteRpsRequest", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters") RecepcionarLoteRpsRequest parameters);

    /**
     *
     * @param parameters
     * @return returns br.com.caelum.estoque.cliente.CancelarNfseResponse
     */
    @WebMethod(operationName = "CancelarNfse", action = "http://notacarioca.rio.gov.br/CancelarNfse")
    @WebResult(name = "CancelarNfseResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    public CancelarNfseResponse cancelarNfse(
            @WebParam(name = "CancelarNfseRequest", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters") CancelarNfseRequest parameters);

    /**
     *
     * @param parameters
     * @return returns br.com.caelum.estoque.cliente.GerarNfseResponse
     */
//    @WebMethod(operationName = "GerarNfse", action = "https://homologacao.notacarioca.rio.gov.br/WSNacional/nfse.asmx")
    @WebMethod(operationName = "GerarNfse", action = "http://notacarioca.rio.gov.br/GerarNfse")
    @WebResult(name = "GerarNfseResponse", targetNamespace = "http://notacarioca.rio.gov.br/", partName = "parameters")
    public GerarNfseResponse gerarNfse(@WebParam(name = "GerarNfseRequest",
            targetNamespace = "http://notacarioca.rio.gov.br/",
            partName = "parameters") GerarNfseRequest parameters);

}
