//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.28 at 03:07:13 PM BRT 
//


package br.com.datagrupo.buyshowloja.webservices.notafiscal.models.nfse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.org.abrasf.abrasf.arquivos.nfse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CompNfse_QNAME = new QName("http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", "CompNfse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.org.abrasf.abrasf.arquivos.nfse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultarNfseEnvio }
     * 
     */
    public ConsultarNfseEnvio createConsultarNfseEnvio() {
        return new ConsultarNfseEnvio();
    }

    /**
     * Create an instance of {@link ConsultarNfseResposta }
     * 
     */
    public ConsultarNfseResposta createConsultarNfseResposta() {
        return new ConsultarNfseResposta();
    }

    /**
     * Create an instance of {@link ConsultarLoteRpsResposta }
     * 
     */
    public ConsultarLoteRpsResposta createConsultarLoteRpsResposta() {
        return new ConsultarLoteRpsResposta();
    }

    /**
     * Create an instance of {@link TcLoteRps }
     * 
     */
    public TcLoteRps createTcLoteRps() {
        return new TcLoteRps();
    }

    /**
     * Create an instance of {@link TcRps }
     * 
     */
    public TcRps createTcRps() {
        return new TcRps();
    }

    /**
     * Create an instance of {@link TcCompNfse }
     * 
     */
    public TcCompNfse createTcCompNfse() {
        return new TcCompNfse();
    }

    /**
     * Create an instance of {@link ListaMensagemRetorno }
     * 
     */
    public ListaMensagemRetorno createListaMensagemRetorno() {
        return new ListaMensagemRetorno();
    }

    /**
     * Create an instance of {@link TcMensagemRetorno }
     * 
     */
    public TcMensagemRetorno createTcMensagemRetorno() {
        return new TcMensagemRetorno();
    }

    /**
     * Create an instance of {@link CancelarNfseEnvio }
     * 
     */
    public CancelarNfseEnvio createCancelarNfseEnvio() {
        return new CancelarNfseEnvio();
    }

    /**
     * Create an instance of {@link TcPedidoCancelamento }
     * 
     */
    public TcPedidoCancelamento createTcPedidoCancelamento() {
        return new TcPedidoCancelamento();
    }

    /**
     * Create an instance of {@link ConsultarSituacaoLoteRpsEnvio }
     * 
     */
    public ConsultarSituacaoLoteRpsEnvio createConsultarSituacaoLoteRpsEnvio() {
        return new ConsultarSituacaoLoteRpsEnvio();
    }

    /**
     * Create an instance of {@link TcIdentificacaoPrestador }
     * 
     */
    public TcIdentificacaoPrestador createTcIdentificacaoPrestador() {
        return new TcIdentificacaoPrestador();
    }

    /**
     * Create an instance of {@link ConsultarSituacaoLoteRpsResposta }
     * 
     */
    public ConsultarSituacaoLoteRpsResposta createConsultarSituacaoLoteRpsResposta() {
        return new ConsultarSituacaoLoteRpsResposta();
    }

    /**
     * Create an instance of {@link ConsultarNfseEnvio.PeriodoEmissao }
     * 
     */
    public ConsultarNfseEnvio.PeriodoEmissao createConsultarNfseEnvioPeriodoEmissao() {
        return new ConsultarNfseEnvio.PeriodoEmissao();
    }

    /**
     * Create an instance of {@link TcIdentificacaoTomador }
     * 
     */
    public TcIdentificacaoTomador createTcIdentificacaoTomador() {
        return new TcIdentificacaoTomador();
    }

    /**
     * Create an instance of {@link TcIdentificacaoIntermediarioServico }
     * 
     */
    public TcIdentificacaoIntermediarioServico createTcIdentificacaoIntermediarioServico() {
        return new TcIdentificacaoIntermediarioServico();
    }

    /**
     * Create an instance of {@link ConsultarNfseRpsEnvio }
     * 
     */
    public ConsultarNfseRpsEnvio createConsultarNfseRpsEnvio() {
        return new ConsultarNfseRpsEnvio();
    }

    /**
     * Create an instance of {@link TcIdentificacaoRps }
     * 
     */
    public TcIdentificacaoRps createTcIdentificacaoRps() {
        return new TcIdentificacaoRps();
    }

    /**
     * Create an instance of {@link EnviarLoteRpsEnvio }
     * 
     */
    public EnviarLoteRpsEnvio createEnviarLoteRpsEnvio() {
        return new EnviarLoteRpsEnvio();
    }

    /**
     * Create an instance of {@link CancelarNfseResposta }
     * 
     */
    public CancelarNfseResposta createCancelarNfseResposta() {
        return new CancelarNfseResposta();
    }

    /**
     * Create an instance of {@link TcCancelamentoNfse }
     * 
     */
    public TcCancelamentoNfse createTcCancelamentoNfse() {
        return new TcCancelamentoNfse();
    }

    /**
     * Create an instance of {@link ConsultarNfseResposta.ListaNfse }
     * 
     */
    public ConsultarNfseResposta.ListaNfse createConsultarNfseRespostaListaNfse() {
        return new ConsultarNfseResposta.ListaNfse();
    }

    /**
     * Create an instance of {@link ConsultarLoteRpsResposta.ListaNfse }
     * 
     */
    public ConsultarLoteRpsResposta.ListaNfse createConsultarLoteRpsRespostaListaNfse() {
        return new ConsultarLoteRpsResposta.ListaNfse();
    }

    /**
     * Create an instance of {@link ConsultarNfseRpsResposta }
     * 
     */
    public ConsultarNfseRpsResposta createConsultarNfseRpsResposta() {
        return new ConsultarNfseRpsResposta();
    }

    /**
     * Create an instance of {@link ConsultarLoteRpsEnvio }
     * 
     */
    public ConsultarLoteRpsEnvio createConsultarLoteRpsEnvio() {
        return new ConsultarLoteRpsEnvio();
    }

    /**
     * Create an instance of {@link EnviarLoteRpsResposta }
     * 
     */
    public EnviarLoteRpsResposta createEnviarLoteRpsResposta() {
        return new EnviarLoteRpsResposta();
    }

    /**
     * Create an instance of {@link TcNfse }
     * 
     */
    public TcNfse createTcNfse() {
        return new TcNfse();
    }

    /**
     * Create an instance of {@link TcValores }
     * 
     */
    public TcValores createTcValores() {
        return new TcValores();
    }

    /**
     * Create an instance of {@link TcInfPedidoCancelamento }
     * 
     */
    public TcInfPedidoCancelamento createTcInfPedidoCancelamento() {
        return new TcInfPedidoCancelamento();
    }

    /**
     * Create an instance of {@link TcEndereco }
     * 
     */
    public TcEndereco createTcEndereco() {
        return new TcEndereco();
    }

    /**
     * Create an instance of {@link TcDadosServico }
     * 
     */
    public TcDadosServico createTcDadosServico() {
        return new TcDadosServico();
    }

    /**
     * Create an instance of {@link TcInfNfse }
     * 
     */
    public TcInfNfse createTcInfNfse() {
        return new TcInfNfse();
    }

    /**
     * Create an instance of {@link TcDadosConstrucaoCivil }
     * 
     */
    public TcDadosConstrucaoCivil createTcDadosConstrucaoCivil() {
        return new TcDadosConstrucaoCivil();
    }

    /**
     * Create an instance of {@link TcDadosPrestador }
     * 
     */
    public TcDadosPrestador createTcDadosPrestador() {
        return new TcDadosPrestador();
    }

    /**
     * Create an instance of {@link TcContato }
     * 
     */
    public TcContato createTcContato() {
        return new TcContato();
    }

    /**
     * Create an instance of {@link TcInfRps }
     * 
     */
    public TcInfRps createTcInfRps() {
        return new TcInfRps();
    }

    /**
     * Create an instance of {@link TcIdentificacaoNfse }
     * 
     */
    public TcIdentificacaoNfse createTcIdentificacaoNfse() {
        return new TcIdentificacaoNfse();
    }

    /**
     * Create an instance of {@link TcSubstituicaoNfse }
     * 
     */
    public TcSubstituicaoNfse createTcSubstituicaoNfse() {
        return new TcSubstituicaoNfse();
    }

    /**
     * Create an instance of {@link TcDadosTomador }
     * 
     */
    public TcDadosTomador createTcDadosTomador() {
        return new TcDadosTomador();
    }

    /**
     * Create an instance of {@link TcInfSubstituicaoNfse }
     * 
     */
    public TcInfSubstituicaoNfse createTcInfSubstituicaoNfse() {
        return new TcInfSubstituicaoNfse();
    }

    /**
     * Create an instance of {@link TcCpfCnpj }
     * 
     */
    public TcCpfCnpj createTcCpfCnpj() {
        return new TcCpfCnpj();
    }

    /**
     * Create an instance of {@link TcIdentificacaoOrgaoGerador }
     * 
     */
    public TcIdentificacaoOrgaoGerador createTcIdentificacaoOrgaoGerador() {
        return new TcIdentificacaoOrgaoGerador();
    }

    /**
     * Create an instance of {@link TcConfirmacaoCancelamento }
     * 
     */
    public TcConfirmacaoCancelamento createTcConfirmacaoCancelamento() {
        return new TcConfirmacaoCancelamento();
    }

    /**
     * Create an instance of {@link TcMensagemRetornoLote }
     * 
     */
    public TcMensagemRetornoLote createTcMensagemRetornoLote() {
        return new TcMensagemRetornoLote();
    }

    /**
     * Create an instance of {@link TcLoteRps.ListaRps }
     * 
     */
    public TcLoteRps.ListaRps createTcLoteRpsListaRps() {
        return new TcLoteRps.ListaRps();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TcCompNfse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", name = "CompNfse")
    public JAXBElement<TcCompNfse> createCompNfse(TcCompNfse value) {
        return new JAXBElement<TcCompNfse>(_CompNfse_QNAME, TcCompNfse.class, null, value);
    }

}
